# Generated by Django 6.0 on 2025-12-22 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capturedtext',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='capturedtext',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captured_texts', to=settings.AUTH_USER_MODEL),
        ),
    ]
